server:
  port: 8080

spring:
  application:
    name: expensys
  datasource:
    url: jdbc:mysql://localhost:3306/expensys
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  flyway:
    baseline-on-migrate: true
  resources:
    add-mappings: true

logging:
  level:
    org.springframework.web: DEBUG
