ALTER TABLE `expenses` MODIFY `category` ENUM(
    'GROCERIES',
    'VEGETABLES_FRUITS_DAIRY_AND_MEAT',
    'MEDICAL',
    'OUTSIDE_FOOD',
    'LOSE_OF_MONEY',
    'SALON_AND_COSMETICS',
    'TRANSPORT',
    'SHOPPING',
    'ENTERTAINMENT',
    'RENT_AND_OTHER_BILLS',
    'OTHERS',
    'INVESTMENTS'
) NOT NULL;
